import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  site: 'https://tl-mechs.com',
  integrations: [
    starlight({
      title: 'TL Mechs Guide',
      description: 'Comprehensive dungeon strategies and mechanics for Throne and Liberty',
      defaultLocale: 'en',
      sidebar: [
        {
          label: 'Altar of Calanthia',
          items: [
            {
              label: 'Dragaryle',
              collapsed: true,
              items: [
                { label: 'OVERVIEW', link: '/altar-of-calanthia/dragaryle/', attrs: { style: 'font-weight: bold' } },
                { label: 'Blue Lines', link: '/altar-of-calanthia/dragaryle/blue-lines/' },
                { label: 'Blue/Yellow Orbs', link: '/altar-of-calanthia/dragaryle/yellow-orbs-blue-orbs/' },
                { label: 'Clone Baiting', link: '/altar-of-calanthia/dragaryle/clone-baiting/' },
                { label: 'Color Circles', link: '/altar-of-calanthia/dragaryle/blue-red-circles/' },
                { label: 'Conal Slam', link: '/altar-of-calanthia/dragaryle/conal-slam/' },
                { label: 'Eye Mech', link: '/altar-of-calanthia/dragaryle/eye-mech/' },
                { label: 'Green Lines', link: '/altar-of-calanthia/dragaryle/green-lines/' },
                { label: 'Petrification Stacks', link: '/altar-of-calanthia/dragaryle/petrification-stacks/' },
                { label: 'Rancorwood', link: '/altar-of-calanthia/dragaryle/rancorwood/' },
                { label: 'Sandstorm', link: '/altar-of-calanthia/dragaryle/sandstorm/' },
                { label: 'Shield', link: '/altar-of-calanthia/dragaryle/shield/' },
                { label: 'Towers', link: '/altar-of-calanthia/dragaryle/towers/' },
              ],
            },
            {
              label: 'Vulkan and Zairos',
              collapsed: true,
              items: [
                { label: 'OVERVIEW', link: '/altar-of-calanthia/vulkan-and-zairos/', attrs: { style: 'font-weight: bold' } },
                {
                  label: 'Phase 1',
                  collapsed: true,
                  items: [
                    { label: 'OVERVIEW', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/', attrs: { style: 'font-weight: bold' } },
                    { label: '(Fire) Conal', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/fire-conal/' },
                    { label: '(Fire) Donuts', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/fire-donuts/' },
                    { label: '(Fire) Floor Eruptions', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/fire-floor-eruptions/' },
                    { label: '(Fire) Jericho Missiles', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/fire-jericho-missiles/' },
                    { label: '(Fire) Meteors', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/fire-meteors/' },
                    { label: '(Fire) Q Blocks', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/fire-q-blocks/' },
                    { label: '(Ice) Beam', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/ice-beam/' },
                    { label: '(Ice) Bowler', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/ice-bowler/' },
                    { label: '(Ice) Cross', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/ice-cross/' },
                    { label: '(Ice) Prison', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/ice-prison/' },
                    { label: '(Ice) Q Blocks', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/ice-q-blocks/' },
                    { label: '(Ice) Shield', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/ice-shield/' },
                    { label: 'Aura/Stacks', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/aura-stacks/' },
                    { label: 'Player Tethers', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/player-tethers/' },
                    { label: 'Wave', link: '/altar-of-calanthia/vulkan-and-zairos/phase-1/wave/' },
                  ],
                },
                {
                  label: 'Phase 2',
                  collapsed: true,
                  items: [
                    { label: 'OVERVIEW', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/', attrs: { style: 'font-weight: bold' } },
                    { label: 'Elemental Crystals', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/elemental-crystals/' },
                    { label: 'Elemental Orbs', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/elemental-orbs/' },
                    { label: 'Elemental Pose', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/elemental-pose/' },
                    { label: 'Elemental Protection', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/elemental-protection/' },
                    { label: 'Elemental Tether', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/elemental-tether/' },
                    { label: 'Fire Conal', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/fire-conal/' },
                    { label: 'Fire Donuts', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/fire-donuts/' },
                    { label: 'Floor Eruptions', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/floor-eruptions/' },
                    { label: 'Ice Beam', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/ice-beam/' },
                    { label: 'Ice Cross', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/ice-cross/' },
                    { label: 'Ice Prisons', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/ice-prisons/' },
                    { label: 'Jump', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/jump/' },
                    { label: 'Meteors', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/meteors/' },
                    { label: 'Shoulder Punches', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/shoulder-punches/' },
                    { label: 'Wave', link: '/altar-of-calanthia/vulkan-and-zairos/phase-2/wave/' },
                  ],
                },
              ],
            },
            {
              label: 'Calanthia',
              collapsed: true,
              items: [
                { label: 'OVERVIEW', link: '/altar-of-calanthia/calanthia/', attrs: { style: 'font-weight: bold' } },
                {
                  label: 'Phase 1',
                  collapsed: true,
                  items: [
                    { label: 'OVERVIEW', link: '/altar-of-calanthia/calanthia/phase-1/', attrs: { style: 'font-weight: bold' } },
                    { label: 'Lightning', link: '/altar-of-calanthia/calanthia/phase-1/lightning/' },
                    { label: 'Tethers', link: '/altar-of-calanthia/calanthia/phase-1/tethers/' },
                    { label: '2 Circle', link: '/altar-of-calanthia/calanthia/phase-1/2-circle/' },
                    { label: 'Roombas', link: '/altar-of-calanthia/calanthia/phase-1/roombas/' },
                    { label: 'Corner Clones', link: '/altar-of-calanthia/calanthia/phase-1/corner-clones/' },
                    { label: 'Pink Seed', link: '/altar-of-calanthia/calanthia/phase-1/pink-seed/' },
                    { label: 'Pulse Block', link: '/altar-of-calanthia/calanthia/phase-1/pulse-block/' },
                    { label: 'Orbs', link: '/altar-of-calanthia/calanthia/phase-1/orbs/' },
                    { label: 'Mirrors', link: '/altar-of-calanthia/calanthia/phase-1/mirrors/' },
                    { label: 'Patrollers', link: '/altar-of-calanthia/calanthia/phase-1/patrollers/' },
                    { label: 'Fake Orbs', link: '/altar-of-calanthia/calanthia/phase-1/fake-orbs/' },
                  ],
                },
                {
                  label: 'Phase 2',
                  collapsed: true,
                  items: [
                    { label: 'OVERVIEW', link: '/altar-of-calanthia/calanthia/phase-2/', attrs: { style: 'font-weight: bold' } },
                    { label: 'Slam Swipes', link: '/altar-of-calanthia/calanthia/phase-2/slam-swipes/' },
                    { label: 'Tethers', link: '/altar-of-calanthia/calanthia/phase-2/tethers/' },
                    { label: 'Crystals', link: '/altar-of-calanthia/calanthia/phase-2/crystals/' },
                    { label: 'Zombies', link: '/altar-of-calanthia/calanthia/phase-2/zombies/' },
                    { label: 'Piano', link: '/altar-of-calanthia/calanthia/phase-2/piano/' },
                    { label: 'Orbs', link: '/altar-of-calanthia/calanthia/phase-2/orbs/' },
                    { label: 'Feathers Stun', link: '/altar-of-calanthia/calanthia/phase-2/feathers-stun/' },
                    { label: 'Detonators', link: '/altar-of-calanthia/calanthia/phase-2/detonators/' },
                    { label: 'Wings', link: '/altar-of-calanthia/calanthia/phase-2/wings/' },
                    { label: 'Patrollers', link: '/altar-of-calanthia/calanthia/phase-2/patrollers/' },
                    { label: 'Enrage Loop', link: '/altar-of-calanthia/calanthia/phase-2/enrage-loop/' },
                  ],
                },
              ],
            },
          ],
        },
        {
          label: '4★ Trials (T5)',
          items: [
            {
              label: 'Colossal Coliseum',
              collapsed: true,
              items: [
                { label: 'OVERVIEW', link: '/trials-4star/colossal-coliseum/', attrs: { style: 'font-weight: bold' } },
                { label: 'Belmore', link: '/trials-4star/colossal-coliseum/belmore/' },
                { label: 'Charging Ghost Tile', link: '/trials-4star/colossal-coliseum/charging-ghost-tile/' },
                { label: 'Conal Attacks', link: '/trials-4star/colossal-coliseum/conal-attacks/' },
                { label: 'Cursed Purple Tile', link: '/trials-4star/colossal-coliseum/cursed-purple-tile/' },
                { label: 'Dodge Roll', link: '/trials-4star/colossal-coliseum/dodge-roll/' },
                { label: 'Fractured Tile', link: '/trials-4star/colossal-coliseum/fractured-tile/' },
                { label: 'Ghost Stampede', link: '/trials-4star/colossal-coliseum/ghost-stampede/' },
                { label: 'Hidden Mark Tiles', link: '/trials-4star/colossal-coliseum/hidden-marked-tile/' },
                { label: 'Nerzatum Charge', link: '/trials-4star/colossal-coliseum/nerzatum-charge/' },
                { label: 'Nerzatum Collapse', link: '/trials-4star/colossal-coliseum/nerzatum-collapse/' },
                { label: 'Orbs', link: '/trials-4star/colossal-coliseum/orbs/' },
                { label: 'Purple Circles', link: '/trials-4star/colossal-coliseum/purple-circles/' },
                { label: 'Radiance Shield Buff', link: '/trials-4star/colossal-coliseum/radiance-shield-buff/' },
                { label: 'Red Circle', link: '/trials-4star/colossal-coliseum/red-circle/' },
                { label: 'Red Squares', link: '/trials-4star/colossal-coliseum/red-squares/' },
                { label: 'Spell Enhancement', link: '/trials-4star/colossal-coliseum/spell-enhancement/' },
              ],
            },
            {
              label: "Fate's Abyss",
              collapsed: true,
              items: [
                { label: 'OVERVIEW', link: '/trials-4star/fates-abyss/', attrs: { style: 'font-weight: bold' } },
                { label: 'Blood Circles', link: '/trials-4star/fates-abyss/blood-circles/' },
                { label: 'Confusion Debuff', link: '/trials-4star/fates-abyss/confusion-debuff/' },
                { label: 'Death Sentence', link: '/trials-4star/fates-abyss/death-sentence/' },
                { label: 'Declaration', link: '/trials-4star/fates-abyss/declaration/' },
                { label: 'Dodge Roll', link: '/trials-4star/fates-abyss/dodge-roll/' },
                { label: 'Floor Blades', link: '/trials-4star/fates-abyss/floor-blades/' },
                { label: 'Mental Collapse', link: '/trials-4star/fates-abyss/mental-collapse/' },
                { label: 'Pillars', link: '/trials-4star/fates-abyss/pillars/' },
                { label: 'Purify Orbs', link: '/trials-4star/fates-abyss/purify-orbs/' },
                { label: 'Spinning Scythes', link: '/trials-4star/fates-abyss/spinning-scythes/' },
                { label: 'Symbol Matching', link: '/trials-4star/fates-abyss/symbol-matching/' },
              ],
            },
          ],
        },
        { label: 'About', link: '/about' },
      ],
      customCss: ['./src/styles/custom.css'],
      head: [],
    }),
  ],
});
